# Generated by Django 3.1.1 on 2020-09-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_auto_20200926_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(upload_to='pro_pic'),
        ),
    ]
